### ISSUE TITLE
FIRST!

### ISSUE THREAD

**Issue by lavilao** [nwg-piotr/nwg-shell-config#2]
sorry, I know this is alpha but I could not hold installing it, so the issue is it crashes when there is no internet on the machine.
```
Traceback (most recent call last):
  File "/usr/bin/nwg-shell-config", line 33, in <module>
    sys.exit(load_entry_point('nwg-shell-config==0.0.5', 'gui_scripts', 'nwg-shell-config')())
  File "/usr/lib/python3.10/site-packages/nwg_shell_config-0.0.5-py3.10.egg/nwg_shell_config/main.py", line 643, in main
    ui = GUI()
  File "/usr/lib/python3.10/site-packages/nwg_shell_config-0.0.5-py3.10.egg/nwg_shell_config/main.py", line 129, in __init__
    self.tz, self.lat, self.long = get_lat_lon()
  File "/usr/lib/python3.10/site-packages/nwg_shell_config-0.0.5-py3.10.egg/nwg_shell_config/tools.py", line 86, in get_lat_lon
    location = geolocator.geocode(tz)
  File "/usr/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/usr/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)_config/tools.py", line 86, in get_lat_lon
    location = geolocator.geocode(tz)
  File "/usr/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/usr/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in 
  File "/usr/lib/python3.10/site-packages/geopy/adapters.py", line 438, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/usr/lib/python3.10/site-packages/geopy/adapters.py", line 460, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=America%2FHavana&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3835df0070>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido'))
```
Keep working and good job, its an amazing software.

**Comment by nwg-piotr** [comment]
I didn't expect it to be run with no internet connection. I'll add a try/Except clause. Thanks for pointing it out.

**Comment by lavilao** [comment]
happy to help and sorry for being an issue

**Comment by nwg-piotr** [comment]
You're no issue. I've been working hard together with [ArchLabs Linux](https://archlabslinux.com/) team to finally have the very first full nwg-shell implementation. Thanks in advance for further feedback.

**Comment by lavilao** [comment]
fixed
