### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by xeruf** [nwg-piotr/nwg-shell-config#52]
Installed and wanted to try it, seems you need a little mkdir -p in there ;)
```sh
❯ nwg-shell-config
Starting sway version
Error loading json: [Errno 2] No such file or directory: '/home/janek/.local/share/nwg-shell/data'
Traceback (most recent call last):
  File "/usr/bin/nwg-shell-config-sway", line 33, in <module>
    sys.exit(load_entry_point('nwg-shell-config==0.5.7', 'gui_scripts', 'nwg-shell-config-sway')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/nwg-shell-config-sway", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/nwg_shell_config/main_sway.py", line 29, in <module>
    shell_data = load_shell_data()
                 ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nwg_shell_config/tools.py", line 360, in load_shell_data
    "installed-version": get_shell_version(),
                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nwg_shell_config/tools.py", line 386, in get_shell_version
    lines = subprocess.check_output("nwg-shell -v".split()).decode('utf-8').splitlines()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nwg-shell'
```

**Comment by xeruf** [comment]
It gets even weirder: I cannot start it even after creating that directory manually, same error!

**Comment by nwg-piotr** [comment]
Have you installed it standalone? It's for use with nwg-shell, and all the dirs are being created by the installer.

**Comment by nwg-piotr** [comment]
Closing due to no further feedback.

**Comment by xeruf** [comment]
Yeah, I am using manjaro-sway and looking for good supplementary GUIs
